// AdDroid OSS — ~/.addroid/config.yaml schema + I/O.
//
// `addroid init` がこの API で config.yaml を生成・整形し、Web/Worker/CLI が
// `readAddroidConfig` で読み込みます。呼び出し側が個人パスを書き込まないよう、
// このモジュールが唯一の書き込みエントリです。

import fs from "node:fs/promises";
import YAML from "yaml";
import { z } from "zod";
import { ensureAddroidPaths, resolveAddroidPaths } from "./paths.js";

/**
 * Regression fix: workspace 全体の execution mode。
 *   - report_only : Meta を絶対に変更しない (観測のみ)
 *   - proposal    : 改善は GitHub PR として提示し、merge が承認境界 (既定)
 *   - auto_apply  : 事前承認済みの safe operations のみ自動実行
 *
 * worker は config.yaml をシードに workspaces.executionMode を初期化し、以後は
 * DB を source of truth として扱う (UI / CLI からの mode 変更が黙って巻き戻ら
 * ないよう、ensureWorkspace は create 時のみこの値を書き込む)。
 */
export const ExecutionModeSchema = z.enum([
  "report_only",
  "proposal",
  "auto_apply",
]);

export type ExecutionMode = z.infer<typeof ExecutionModeSchema>;

export const AddroidConfigSchema = z.object({
  version: z.literal(1),
  workspace: z.object({
    slug: z.string().min(1),
    displayName: z.string().min(1),
    executionMode: ExecutionModeSchema.default("proposal"),
  }),
  database: z.object({
    urlRef: z.string().min(1).describe("DATABASE_URL の解決元 (例: '.env.local')"),
  }),
  web: z
    .object({
      hostname: z.string().default("127.0.0.1"),
      port: z.number().int().min(1).max(65535).default(3000),
    })
    .default({ hostname: "127.0.0.1", port: 3000 }),
  github: z
    .object({
      opsRepo: z
        .object({
          owner: z.string().min(1),
          name: z.string().min(1),
          defaultBranch: z.string().default("main"),
        })
        .optional(),
    })
    .default({}),
});

export type AddroidConfig = z.infer<typeof AddroidConfigSchema>;

export class ConfigParseError extends Error {
  readonly file: string;
  readonly issues: string[];
  constructor(file: string, issues: string[]) {
    super(`Failed to parse ${file}: ${issues.join("; ") || "unknown error"}`);
    this.name = "ConfigParseError";
    this.file = file;
    this.issues = issues;
  }
}

/**
 * the current implementation で `addroid init` が初期生成する config.yaml の既定値を返す。
 * `version: 1` 以外の値はすべてプレースホルダーで、ユーザーが後から書き換える前提。
 */
export function defaultAddroidConfig(env: NodeJS.ProcessEnv = process.env): AddroidConfig {
  const databaseUrlRef = env.DATABASE_URL ? "(env)" : ".env.local";
  return {
    version: 1,
    workspace: {
      slug: "default",
      displayName: "Default Workspace",
      executionMode: "proposal",
    },
    database: { urlRef: databaseUrlRef },
    web: { hostname: "127.0.0.1", port: 3000 },
    github: {},
  };
}

/**
 * `~/.addroid/config.yaml` を読み込む。ファイルが無ければ null。
 * Zod 検証に失敗した場合は ConfigParseError を投げる (呼び出し側で actionable error にする)。
 */
export async function readAddroidConfig(
  env: NodeJS.ProcessEnv = process.env
): Promise<AddroidConfig | null> {
  const { configFile } = resolveAddroidPaths(env);
  let raw: string;
  try {
    raw = await fs.readFile(configFile, "utf8");
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return null;
    throw err;
  }
  const parsed = YAML.parse(raw);
  const result = AddroidConfigSchema.safeParse(parsed);
  if (!result.success) {
    throw new ConfigParseError(configFile, result.error.issues.map((i) => i.message));
  }
  return result.data;
}

/**
 * `~/.addroid/config.yaml` を書き込む。ディレクトリが無ければ作成する。
 * 既存ファイルと内容が完全一致する場合は disk への書き込みをスキップする (mtime を保つ)。
 */
export async function writeAddroidConfig(
  config: AddroidConfig,
  env: NodeJS.ProcessEnv = process.env
): Promise<{ wrote: boolean; path: string }> {
  AddroidConfigSchema.parse(config);
  const paths = await ensureAddroidPaths(env);
  const banner =
    "# AdDroid OSS local config. Generated by `addroid init` and editable.\n" +
    "# Do not commit this file. Secrets belong in secrets.local.yaml.\n";
  const body = YAML.stringify(config);
  const next = banner + body;
  let current: string | null = null;
  try {
    current = await fs.readFile(paths.configFile, "utf8");
  } catch {
    /* not present */
  }
  if (current === next) return { wrote: false, path: paths.configFile };
  await fs.writeFile(paths.configFile, next, { encoding: "utf8", mode: 0o600 });
  await fs.chmod(paths.configFile, 0o600).catch(() => undefined);
  return { wrote: true, path: paths.configFile };
}
